defaults: &defaults
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres
  password: 
  host: localhost

development:
  <<: *defaults
  database: tarot_api_dev

test:
  <<: *defaults
  database: tarot_api_test
