# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Card.create(name: '', short_meaning: '', full_meaning: '', up: '', reverse: '', face_image: File.new("#{Rails.root}/lib/images/deck/<card>"))

Card.create(name: 'The Fool', short_meaning: 'A new phase in life and an urge to explore new aspects of yourself. Decisions have to be thought through carefully; don’t lead yourself into unsuitable or difficult situations.', full_meaning: 'Something new is starting for the Subject which could be a new relationship, job or home.   This is likely to be an exciting time for them with lots of hope and anticipation for the future.  The Subject is so caught up in the buzz of it all that they may not be thinking as clearly as they should.The Subject should be receptive to change and doing things they wouldn’t normally.  In doing so they will learn about different sides of themself and even discover new things they want out of life. The Subject will be feeling happy, confident and ready to face what is ahead of them.Notes on the image:  The Fool is crossing a bridge to travel to a new kingdom and so this picture illustrates someone embarking on a new journey, a new adventure or start. He carries a small satchel containing his belongings which is representative of the subject being “all in” leaving the past behind and starting completely afresh.He’s not focussed or rushing, in fact he’s playing a flute and wandering along without a care in the world. Almost immediately before him is a hole in the bridge and he is at risk of falling through into the deep, fast moving river below. He’s naively not paying attention to what is ahead of him which could lead him into trouble.', up: 'innocence, new beginnings, free spirit', reverse: 'recklessness, taken advantage of, inconsideration', face_image: File.new("#{Rails.root}/lib/images/deck/00_Fool.jpg"))
Card.create(name: 'The Magician', short_meaning: 'A crossroads. An opportunity for constructive change and for you to establish a new, better reality for yourself. You have everything you need to succeed. Capitalise on your skills and creative talents.', full_meaning: 'When The Magician appears it is time for the Subject to make a decision about something big which could set them off in a new direction in life. The Subject has the capability to achieve whatever it is they choose and they should be guided by what they feel inside, not necessarily what is expected of them. This card advises they should do whatever their gut is telling them to.This card comes up when it is time for the Subject to take some serious steps forward in life. If the Subject is not where they want or need to be and is doing nothing to resolve it, The Magician will appear. When he does, the Subject is forced to face a situation or a decision between their existing lives and a new direction.Notes on the image:  The Magician stands at a crossroads indicating that we have to decide what route or path to take now. There are no clear directions on the sign post, therefore we are required to make a choice with little information. The Magician encourages us to follow our instinct and to use our innate abilities and to summon up those qualities that lie hidden in our psyche.The Magician is magically manipulating a sword, pentacle, wand and cup between his hands. These objects represent a range of different skills, abilities, tools and resources that we all have – such as intellect, vision, common sense, bravado, and charm – that we can use to maximise our success. The Magician prompts us to think carefully about how we can utilise those skills and resources to achieve the best outcome possible.', up: 'willpower, desire, creation, manifestation', reverse: 'trickery, illusions, out of touch', face_image: File.new("#{Rails.root}/lib/images/deck/01_Magician.jpg"))
