# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
## Card.create(name: '', short_meaning: '', full_meaning: '', up: '', reverse: '', face_image: File.new("#{Rails.root}/lib/images/deck/<card>"))
Card.create(name: 'The Fool', short_meaning: 'A new phase in life and an urge to explore new aspects of yourself. Decisions have to be thought through carefully; don’t lead yourself into unsuitable or difficult situations.', full_meaning: 'Something new is starting for the Subject which could be a new relationship, job or home. This is likely to be an exciting time for them with lots of hope and anticipation for the future. The Subject is so caught up in the buzz of it all that they may not be thinking as clearly as they should. The Subject should be receptive to change and doing things they wouldn’t normally. In doing so they will learn about different sides of themself and even discover new things they want out of life. The Subject will be feeling happy, confident and ready to face what is ahead of them.', up: 'innocence, new beginnings, free spirit', reverse: 'recklessness, taken advantage of, inconsideration', face_image: File.new("#{Rails.root}/lib/images/deck/00_Fool.jpg"))

Card.create(name: 'The Magician', short_meaning: 'A crossroads. An opportunity for constructive change and for you to establish a new, better reality for yourself. You have everything you need to succeed. Capitalise on your skills and creative talents.', full_meaning: 'When The Magician appears it is time for the Subject to make a decision about something big which could set them off in a new direction in life. The Subject has the capability to achieve whatever it is they choose and they should be guided by what they feel inside, not necessarily what is expected of them. This card advises they should do whatever their gut is telling them to.This card comes up when it is time for the Subject to take some serious steps forward in life. If the Subject is not where they want or need to be and is doing nothing to resolve it, The Magician will appear. When he does, the Subject is forced to face a situation or a decision between their existing lives and a new direction.', up: 'willpower, desire, creation, manifestation', reverse: 'trickery, illusions, out of touch', face_image: File.new("#{Rails.root}/lib/images/deck/01_Magician.jpg"))
